version: '3.8'
services:

  #
  # The Curity Identity Server is used for passkey logins
  #
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    #image: curity/idsvr-unstable:9.1.0-25ae7d1d95
    hostname: identityserver
    ports:
     - 6749:6749
     - 8443:8443
    volumes:
     - ./license.json:/opt/idsvr/etc/init/license/license.json
     - ./config/0-base-config.xml:/opt/idsvr/etc/init/config.xml
     - ./config/create-account.properties:/opt/idsvr/usr/share/messages/overrides/en/create-account.properties
     - ./custom.properties:/opt/idsvr/usr/share/messages/overrides/en/custom.properties
     #- ./identityserver.plugins.authenticators.username-1.3.1.jar:/opt/idsvr/lib/plugins/authenticators.username/identityserver.plugins.authenticators.username-1.3.1.jar
    environment:
      ADMIN: 'true'
      LOGGING_LEVEL: 'INFO'
      RUNTIME_BASE_URL: "${RUNTIME_BASE_URL}"

  #
  # A database where passkeys stored against user accounts can be queried
  #
  curity-data:
    image: postgres:latest
    hostname: dbserver
    ports:
     - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data-backup.sql:/docker-entrypoint-initdb.d/data-backup.sql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password1'
      POSTGRES_DB: 'idsvr'

  #
  # A mock email server that allows email recovery flows for passkeys users
  #
  smtp-server:
    image: maildev/maildev:latest
    hostname: smtpserver
    environment:
      MAILDEV_INCOMING_USER: 'noreply@example.com'
      MAILDEV_INCOMING_PASSWORD: 'Password1'
    ports:
      - 1080:1080
